name: "Release"
on:
  workflow_dispatch: ~
  push:
    branches:
      - "main"
jobs:
  Pack-Frontend-File:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Packaging
        run: for f in `ls -d */ | tr "/" " "`; do mv ${f} mojoconsole; zip -r ${f}.zip mojoconsole; rm -rf mojoconsole; done
      - name: Automatic create a relase
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Frontend package - unzip to `plugins` folder"
          files: |
            *.zip